export const movies = [
    {
        id: 1,
        name: 'Top Gun: Maverick',
        poster: 'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg',
        year: 2022,
        runtime: 130,
        categories: ['action', 'drama'],
        'release-date': '2022-05-27',
        director: 'Joseph Kosinski',
        actors: ['Tom Cruise', 'Jennifer Connelly', 'Miles Teller'],
        storyline:
            "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to ...",
    },
    {
        id: 2,
        name: 'Raya and the Last Dragon',
        poster: 'https://m.media-amazon.com/images/M/MV5BZWNiOTc4NGItNGY4YS00ZGNkLThkOWEtMDE2ODcxODEwNjkwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
        year: 2021,
        runtime: 124,
        categories: ['animation', 'action', 'adventure'],
        'release-date': '2021-03-04',
        director: ['Don Hall', 'Carlos López Estrada'],
        writer: ['Qui Nguyen', 'Adele Lim'],
        actors: [
            'Kelly Marie Tran',
            'Awkwafina',
            'Izaac Wang',
            'Gemma Chan',
            'Daniel Dae Kim',
            'Benedict Wong',
        ],
        storyline:
            "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. However, when sinister monsters known as the Druun threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, those same monsters have returned, and it's up to a lone warrior to track down the last dragon and stop the Druun for good.",
    },
    {
        id: 3,
        name: 'Aladdin',
        poster: 'https://m.media-amazon.com/images/M/MV5BY2Q2NDI1MjUtM2Q5ZS00MTFlLWJiYWEtNTZmNjQ3OGJkZDgxXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg',
        year: 2019,
        runtime: 128,
        categories: ['adventure', 'family', 'fantasy', 'musical', 'romance'],
        'release-date': '2019-05-22',
        director: 'Guy Ritchie',
        writer: ['John August', 'Guy Ritchie'],
        actors: [
            'Will Smith',
            'Mena Massoud',
            'Naomi Scott',
            'Marwan Kenzari',
            'Navid Negahban',
            'Nasim Pedrad',
            'Billy Magnussen',
            'Jordan A. Nash',
            'Taliyah Blair',
            'Aubrey Lin',
            'Amir Boutrous',
            'Numan Acar',
            'Omari Bernard',
            'Nathaniel Ellul',
            'Sebastien Torkia',
        ],
        storyline:
            'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.',
    },
    {
        id: 4,
        name: 'Fast & Furious Presents: Hobbs & Shaw',
        poster: 'https://m.media-amazon.com/images/M/MV5BOTIzYmUyMmEtMWQzNC00YzExLTk3MzYtZTUzYjMyMmRiYzIwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
        year: 2019,
        runtime: 136,
        categories: ['action', 'adventure', 'comedy', 'mystery'],
        'release-date': '2019-07-13',
        director: 'David Leitch',
        writer: ['Chris Morgan', 'Drew Pearce'],
        actors: [
            'Dawyne Johnson',
            'Jason Statham',
            'Idris Elba',
            'Vanessa Kirby',
            'Helen Mirren',
            'Ryan Reynolds',
        ],
        storyline:
            "Brixton Lorr is a cybernetically enhanced soldier who possesses superhuman strength, a brilliant mind and a lethal pathogen that could wipe out half of the world's population. It's now up to hulking lawman Luke Hobbs and lawless operative Deckard Shaw to put aside their past differences and work together to prevent the seemingly indestructible Lorr from destroying humanity.",
    },
    {
        id: 5,
        name: 'Godzilla: King of the Monsters',
        poster: 'https://m.media-amazon.com/images/M/MV5BOGFjYWNkMTMtMTg1ZC00Y2I4LTg0ZTYtN2ZlMzI4MGQwNzg4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
        year: 2019,
        runtime: 132,
        categories: ['action', 'adventure', 'fantasy', 'sci-fi'],
        'release-date': '2019-05-29',
        director: 'Michael Dougherty',
        writer: ['Michael Dougherty', 'Zach Shields', 'Max Borenstein'],
        actors: [
            'Kyle Chandler',
            'Vera Farmiga',
            'Millie Bobby Brown',
            'Ken Watanabe',
            'Ziyi Zhang',
            'Bradley Whitford',
            'Sally Hawkins',
            'Charles Dance',
            'Thomas Middleditch',
            'Aisha Hinds',
            "O'Shea Jackson Jr.",
            'David Strathairn',
            'Anthony Ramos',
            'Elizabeth Faith Ludlow',
            'Jonathan Howard',
        ],
        storyline:
            "The new story follows the heroic efforts of the crypto-zoological agency Monarch as its members face off against a battery of god sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three headed King Ghidorah. When these ancient superspecies, thought to be mere myths, rise again, they all vie for supremacy, leaving humanity's very existence hanging in the balance.",
    },
    {
        id: 6,
        name: 'Joker',
        poster: 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
        year: 2019,
        runtime: 122,
        categories: ['Crime', 'Drama', 'Thriller'],
        'release-date': '2019-09-28',
        director: 'Todd Phillips',
        writer: ['Todd Phillips', 'Scott Silver'],
        actors: [
            'Joaquin Phoenix',
            'Robert De Niro',
            'Zazie Beetz',
            'Frances Conroy',
            'Brett Cullen',
        ],
        storyline:
            'In Gotham City, mentally-troubled comedian Arthur Fleck embarks on a downward-spiral of social revolution and bloody crime. This path brings him face-to-face with his infamous alter-ego: "The Joker".',
    },
    {
        id: 7,
        name: 'Spider-Man: Far from Home',
        poster: 'https://m.media-amazon.com/images/M/MV5BMGZlNTY1ZWUtYTMzNC00ZjUyLWE0MjQtMTMxN2E3ODYxMWVmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
        year: 2019,
        runtime: 129,
        categories: ['action', 'adventure', 'sci-fi'],
        'release-date': '2019-07-02',
        director: 'Jon Watts',
        writer: ['Chris McKenna', 'Erik Sommers', 'Stan Lee', 'Steve Dikto'],
        actors: [
            'Tom Holland',
            'Samuel L.Jackson',
            'Jake Gyllenhaal',
            'Marisa Tomei',
            'Jon Favreau',
            'Zendaya',
            'Jacob Batalon',
            'Tony Revolori',
            'Angourie Rice',
            'Remy Hii',
            'Martin Starr',
            'Jorge Lendeborg Jr.',
            'Cobie Smulders',
            'Numan Acar',
        ],
        storyline:
            "Our friendly neighborhood Super Hero decides to join his best friends Ned, MJ, and the rest of the gang on a European vacation. However, Peter's plan to leave super heroics behind for a few weeks are quickly scrapped when he begrudgingly agrees to help Nick Fury uncover the mystery of several elemental creature attacks, creating havoc across the continent.",
    },
    {
        id: 8,
        name: 'Kung Fu Panda 3',
        poster: 'https://m.media-amazon.com/images/M/MV5BMTUyNzgxNjg2M15BMl5BanBnXkFtZTgwMTY1NDI1NjE@._V1_SX300.jpg',
        year: 2016,
        runtime: 95,
        categories: [
            'animation',
            'action',
            'adventure',
            'comedy',
            'family',
            'fantasy',
        ],
        'release-date': '2016-01-29',
        director: ['Jennifer Yuh Nelson', 'Alessandro Carloni'],
        writer: ['Jonathan Aibel', 'Glenn Berger'],
        actors: ['Jack Black', 'Bryan Cranston', 'Dustin Hoffman'],
        storyline:
            'Continuing his "legendary adventures of awesomeness", Po must face two hugely epic, but different threats: one supernatural and the other a little closer to his home.',
    },
]
